apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: codenameninja/subscriber
      context: ../
      sync:
        infer:
          - 'apps/api/subscriber/src/**/*.ts'
      docker:
        dockerfile: apps/api/subscriber/Dockerfile.dev
  local:
    push: false
manifests:
  rawYaml:
    - ../infra/k8s-dev/k8s/subscriber*
deploy:
  kubectl: {}