apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-auth-depl
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-auth
  template:
    metadata:
      labels:
        app: frontend-auth
    spec:
      containers:
        - name: frontend-auth
          image: codenameninja/frontend-auth
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-auth-srv
spec:
  selector:
    app: frontend-auth
  ports:
    - name: frontend-auth
      protocol: TCP
      port: 8082
      targetPort: 8082
