apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.name }}-hpa"
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.name }}-depl"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes\
  metrics:
{{- toYaml .Values.hpa.metrics | nindent 4 }}