apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-srv"
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: "{{ .Values.name }}"
  type: NodePort
  ports:
    - name: "{{ .Values.name }}"
      protocol: TCP
      port: 3000
      targetPort: 3000