apiVersion: v1
kind: PersistentVolume
metadata:
  name: scheduler-data
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/Shared/scheduler
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: scheduler-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-data
  labels:
    volume-type: nats
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  hostPath:
    path: /Users/Shared/nats/data
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jetstream-pvc
    namespace: default