apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn
type: Opaque
data:
  SENTRY_DSN: aHR0cHM6Ly80Mjg4OTFlNjg0NmM0M2RlOTNkOGZkY2M2MmNkODc5MkBvNDUwMzk2OTUwMjg1NTE2OC5pbmdlc3Quc2VudHJ5LmlvLzQ1MDM5NzA0NTg1MDExMjA=

---
apiVersion: v1
kind: Secret
metadata:
  name: site-url
type: Opaque
data:
  SITE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw

---
apiVersion: v1
kind: Secret
metadata:
  name: api-url
type: Opaque
data:
  API_URL: aHR0cDovL2xvY2FsaG9zdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-api-key
type: Opaque
data:
  SENDGRID_API_KEY: U0cuaXlDNGhrNmNSay15QTlwek9YNlBmZy5HSXB6OXN4dWRPTnBoMzB0RU93SGlkNmVRUllzWm13NWpNTHVsY25ud1Vn

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-api-key
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVJUVjZTQjJESk1LWFJFVTQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-api-secret
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: WURBcFpHMWFqcDdhNzJ1TnZiazV3eVlFdUQxVGJaTFJOMVpJUkVtcg==

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-key
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVJUVjZTQjJEQVRKN1NFUEw=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-secret
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: QkF3WnQwdTA3aGJzTTVwOFBZcm1VSG02a3UraG1CdG92aFdoeEgrbA==

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-client-id
type: Opaque
data:
  AWS_COGNITO_CLIENT_ID: MzhubWd0cWFkYTM1cjNmaGllYTJqaHZhaW8=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-client-secret
type: Opaque
data:
  AWS_COGNITO_CLIENT_SECRET: YTdwY3IycHNuN280M244ZjJxZTJwNXRvbjM0Ym1lNGltbGdmazQzZ3A2N21wOTE5a21r

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-region
type: Opaque
data:
  AWS_COGNITO_REGION: ZXUtbm9ydGgtMQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cognito-pool-id
type: Opaque
data:
  AWS_COGNITO_POOL_ID: ZXUtbm9ydGgtMV92ZWpuNjhHU3AK