apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: codenameninja/admin:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_ENVIRONMENT
              value: "staging"

---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
