name: "logging"
deployment:
  tag: "staging"
  repository: "codenameninja"
  resources:
    requests:
      cpu: 150m
      memory: 124Mi
    limits:
      cpu: 200m
      memory: 500Mi
database:
  url: mongodb+srv://staging_user:ooToR3JHdc2K54Tx@auth.uqgcn8c.mongodb.net/logging
hpa:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Pods
      pods:
        metric:
          name: http_requests_total
        target:
          type: AverageValue
          averageValue: 1000m