FROM node:20.2-alpine3.17

WORKDIR /app

COPY package.json yarn.lock ./

COPY libs/Core libs/Core

COPY apps/api/send-notification apps/api/send-notification

RUN yarn install

RUN yarn workspace @channel360/core build

WORKDIR /app/apps/api/send-notification

CMD ["yarn", "start"]