FROM node:20.2-alpine3.17

WORKDIR /app

COPY package.json yarn.lock ./

COPY libs libs

COPY apps/api/templates apps/api/templates

RUN yarn install

RUN yarn workspace @channel360/core build

WORKDIR /app/apps/api/templates

CMD ["yarn", "start"]