FROM node:20.2-alpine3.17

WORKDIR /app

COPY package.json yarn.lock ./

COPY libs/Core libs/Core

COPY apps/api/plan apps/api/plan

RUN yarn install

RUN yarn workspace @channel360/core build

WORKDIR /app/apps/api/plan

CMD ["yarn", "start"]