apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
        - name: organization
          image: codenameninja/organization:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "150Mi"
              cpu: "75m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb+srv://dv9na3bZdzz:aBRXoDJFJ9OX2c9Q@production.x7wnh49.mongodb.net/organization
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ADMIN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: ADMIN_JWT_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: SENTRY_DSN
            - name: SITE_URL
              valueFrom:
                secretKeyRef:
                  name: site-url
                  key: SITE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-id
                  key: AWS_COGNITO_CLIENT_ID
            - name: AWS_COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-secret
                  key: AWS_COGNITO_CLIENT_SECRET
            - name: AWS_COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-region
                  key: AWS_COGNITO_REGION
            - name: AWS_COGNITO_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-pool-id
                  key: AWS_COGNITO_POOL_ID
---
apiVersion: v1
kind: Service
metadata:
  name: organization-srv
spec:
  selector:
    app: organization
  ports:
    - name: organization
      protocol: TCP
      port: 3000
      targetPort: 3000
