apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-depl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: codenameninja/webhook:latest
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb+srv://dv9na3bZdzz:aBRXoDJFJ9OX2c9Q@production.x7wnh49.mongodb.net/conversation
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SMOOCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smooch-username-secret
                  key: SMOOCH_USERNAME
            - name: SMOOCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smooch-password-secret
                  key: SMOOCH_PASSWORD
            - name: ADMIN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: ADMIN_JWT_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: SENTRY_DSN
            - name: AWS_COGNITO_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-pool-id
                  key: AWS_COGNITO_POOL_ID
            - name: AWS_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-id
                  key: AWS_COGNITO_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-srv
spec:
  selector:
    app: webhook
  ports:
    - name: webhook
      protocol: TCP
      port: 3000
      targetPort: 3000
