apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrations
  template:
    metadata:
      labels:
        app: integrations
    spec:
      containers:
        - name: integrations
          image: codenameninja/integrations
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://integrations-mongo-srv:27017/integrations
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: integrations-srv
spec:
  selector:
    app: integrations
  ports:
    - name: integrations
      protocol: TCP
      port: 3000
      targetPort: 3000
