apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: logging
          image: codenameninja/logging
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://logging-mongo-srv:27017/logging
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SMOOCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smooch-username-secret
                  key: SMOOCH_USERNAME
            - name: SMOOCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smooch-password-secret
                  key: SMOOCH_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-secret
                  key: AWS_COGNITO_CLIENT_SECRET
            - name: AWS_COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-region
                  key: AWS_COGNITO_REGION
            - name: AWS_COGNITO_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-pool-id
                  key: AWS_COGNITO_POOL_ID
            - name: AWS_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-id
                  key: AWS_COGNITO_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: logging-srv
spec:
  selector:
    app: logging
  ports:
    - name: logging
      protocol: TCP
      port: 3000
      targetPort: 3000
