apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: codenameninja/scheduler
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://scheduler-mongo-srv:27017/scheduler
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-srv
spec:
  selector:
    app: scheduler
  ports:
    - name: scheduler
      protocol: TCP
      port: 3000
      targetPort: 3000
