apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-sync-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-sync
  template:
    metadata:
      labels:
        app: template-sync
    spec:
      containers:
        - name: template-sync
          image: codenameninja/template-sync
          env:
            - name: NATS_URL
              value: http://nats-jet-0:4222, http://nats-jet-1:4222, http://nats-jet-2:4222
            - name: CLUSTER_ID
              value: channel
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb+srv://dev:Something23@development.rputw2o.mongodb.net/templates
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: SENTRY_DSN
            - name: SMOOCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smooch-username-secret
                  key: SMOOCH_USERNAME
            - name: SMOOCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smooch-password-secret
                  key: SMOOCH_PASSWORD
            - name: AWS_COGNITO_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-pool-id
                  key: AWS_COGNITO_POOL_ID
            - name: AWS_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cognito-client-id
                  key: AWS_COGNITO_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: template-sync-srv
spec:
  selector:
    app: template-sync
  ports:
    - name: template-sync
      protocol: TCP
      port: 3000 # Application port
      targetPort: 3000 # Application port
    - name: debug
      protocol: TCP
      port: 9229 # Debugging port
      targetPort: 9229 # Debugging port
  # Port-forwarding rule to forward port 9229 to the pod
  # This allows external access to the debugging port
  # Replace "<YOUR-EXTERNAL-PORT>" with the desired external port
  # For example, if you want to expose it on port 9229 externally, you can use:
  # nodePort: 9229
  type: NodePort
