name: deploy-reports-service

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "apps/api/reports/**"

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.ref_name == 'main' && 'latest' || 'staging' }}
          docker build -f apps/api/reports/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/reports:$IMAGE_TAG --build-arg="PM2_PUBLIC_KEY=${{ secrets.PM2_PUBLIC_KEY }}" --build-arg="PM2_SECRET_KEY=${{ secrets.PM2_SECRET_KEY }}" .
      - name: Log into Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: |
          IMAGE_TAG=${{ github.ref_name == 'main' && 'latest' || 'staging' }}
          docker push ${{ secrets.DOCKER_USERNAME }}/reports:$IMAGE_TAG

  restart-deployment:
    needs: [ build-and-push ]
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - name: Setup Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DOCTL_TOKEN}}

      - name: Update Kubernetes Config
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
      - name: Restart Authentication Deployment
        run: kubectl rollout restart deployment reports-depl
