name: test-conversation-router-service

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - "apps/api/conversation-router/**"
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - "apps/api/conversation-router/package.json"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Build @channel360/core
        run: |
          yarn workspace @channel360/core install
          yarn workspace @channel360/core build
      - name: Run Tests
        working-directory: apps/api/conversation-router
        run: |
          yarn install
          yarn run test:ci --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: conversation-router-service
          threshold: '5%'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}